apiVersion : apps/v1
kind: Deployment
metadata:
  name: shivakantdixittestskd 
spec:
 selector:
    matchLabels:
      name: shivakantdixittestskd
  replicas: 1
  template:
    metadata:
      labels:
        app: shivakantdixittestskd 
    spec:
      containers:
        - name: shivakantdixittestskd 
          image: skdcr.azurecr.io/shivakantdixittestskd
          ports:
          - containerPort: 80
